import os

# Authenticated user
USERNAME = os.getenv('TWITTER_USERNAME').lower()

MENTION_EXPIRY_TIME_IN_SECONDS = 60
MENTION_CHECK_INTERVAL_IN_SECONDS = 15
LAST_MENTION_FILE = 'last_mention'
FONTS_DIR = 'fonts/'
QUOTES_DIR = 'quotes/'

IMAGES_DIR = 'images/'
IMAGE_STORE_FILE=f'{IMAGES_DIR}store.json'
IMAGE_EXT = '.jpg'
DEFAULT_IMAGE_KIND='Nature'
MIN_MATCH_SIMILARITY=0.5

QUOTE_FONT_SIZE = 36
AUTHOR_FONT_SIZE = 24
WATERMARK_FONT_SIZE = 16
MAX_CHARS_PER_LINE = 40
GAP_SIZE = 8
TEXT_COLOR = (255, 255, 255)

WATERMARK_TEXT = f'@{USERNAME}'

## Twitter API Keys

CONSUMER_KEY = os.getenv('TWITTER_CONSUMER_KEY')
CONSUMER_SECRET = os.getenv('TWITTER_CONSUMER_SECRET')
ACCESS_TOKEN = os.getenv('TWITTER_ACCESS_TOKEN')
ACCESS_TOKEN_SECRET = os.getenv('TWITTER_ACCESS_TOKEN_SECRET')

## Discord

DISCORD_WEBHOOK_URL = os.getenv('DISCORD_WEBHOOK_URL')